In [ ]:
Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its
application.

In [ ]:
min-max scaling  is a data processing technique use to scale the feature of the dataset to a specific range[0,1]
specifically used when the data is not normally distributed 
formula
x=original value
normalised value= x- min (x)/max(x)-min(x)

In [1]:
import pandas as pd  
from sklearn.preprocessing import MinMaxScaler  
data = {  
    'A': [10, 15, 10, 20, 25],  
    'B': [200, 220, 240, 210, 230],  
    'C': [1, 2, 1, 3, 0]  
}  
df = pd.DataFrame(data)    
scaler = MinMaxScaler()  
scaled_data = scaler.fit_transform(df)  
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)  

print("Original DataFrame:")  
print(df)  
print("\nScaled DataFrame:")  
print(scaled_df)

Original DataFrame:
    A    B  C
0  10  200  1
1  15  220  2
2  10  240  1
3  20  210  3
4  25  230  0

Scaled DataFrame:
          A     B         C
0  0.000000  0.00  0.333333
1  0.333333  0.50  0.666667
2  0.000000  1.00  0.333333
3  0.666667  0.25  1.000000
4  1.000000  0.75  0.000000


In [ ]:
Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?
Provide an example to illustrate its application.

In [ ]:
The Unit Vector technique, is a form of feature scaling that rescales the feature vectors to have a length of 1.
This transformation converts each feature vector into a unit vector, thereby standardizing the direction of the
data points without changing their relationships. 
formula
unit vector=x/||x||

Min-Max Scaling
Rescales the data to a specific range[0,1].
The relative differences between features are preserved, but those features are brought to a common range.

Unit Vector Technique
Focuses on the direction of the data rather than the actual values. It normalizes the scale, which is 
particularly useful for direction-sensitive algorithms.
Scales the data such that the magnitude of each vector is 1.


In [4]:
import pandas as pd  
from sklearn.preprocessing import normalize
data = {  
    'A': [10, 15, 10, 20, 25],  
    'B': [200, 220, 240, 210, 230],  
    'C': [1, 2, 1, 3, 0]  
}  
df = pd.DataFrame(data)  
normalize(df[['A', 'B', 'C']])

array([[0.04993699, 0.99873989, 0.0049937 ],
       [0.06802109, 0.99764266, 0.00906948],
       [0.04163018, 0.99912442, 0.00416302],
       [0.09479951, 0.99539482, 0.01421993],
       [0.10805918, 0.99414446, 0.        ]])

In [5]:
import pandas as pd
pd.DataFrame(normalize(df[['A', 'B', 'C']]),
             columns=['A', 'B', 'C'])

A         B         C
0  0.049937  0.998740  0.004994
1  0.068021  0.997643  0.009069
2  0.041630  0.999124  0.004163
3  0.094800  0.995395  0.014220
4  0.108059  0.994144  0.000000

In [ ]:
Q3. What is PCA, and how is it used in dimensionality reduction? Provide an
example to illustrate its application.

In [ ]:
PCA is a statistical technique used for dimensionality reduction while preserving as much variance as possible in a dataset.
It transforms a high-dimensional dataset into a lower-dimensional one by identifying the directions in which the data varies 
the most. Essentially, PCA helps to simplify complex datasets by reducing the number of dimensions while retaining the most
important features.

In [ ]:
Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature
Extraction? Provide an example to illustrate this concept.

In [ ]:
PCA transformed the original features into  principal components, which capture the most variability in the data. These 
principal components can be used as features in subsequent analysis or modeling tasks, thereby reducing dimensional 
complexity while retaining the most important information. PCA serves as an effective technique for feature extraction, 
especially when working with high-dimensional data.

In [ ]:
Q5. You are working on a project to build a recommendation system for a food delivery service. The 
dataset contains features such as price, rating, and delivery time. Explain how you would use Min-Max
scaling to preprocess the data.

In [3]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df = pd.DataFrame({
    'price': [15.99, 23.50, 10.75, 27.20],
    'rating': [4.7, 3.8, 4.3, 4.9],
    'delivery_time': [30, 45, 20, 35]
})

from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
min_max.fit(df[['price','rating','delivery_time']])
min_max.fit_transform(df[['price','rating','delivery_time']])

array([[0.31854103, 0.81818182, 0.4       ],
       [0.77507599, 0.        , 1.        ],
       [0.        , 0.45454545, 0.        ],
       [1.        , 1.        , 0.6       ]])

In [ ]:
Q6. You are working on a project to build a model to predict stock prices. The dataset contains many
features, such as company financial data and market trends. Explain how you would use PCA to reduce 
the
dimensionality of the dataset.

In [6]:
import pandas as pd
pd.DataFrame(normalize(df[['A', 'B', 'C']]),
             columns=['A', 'B', 'C'])

A         B         C
0  0.049937  0.998740  0.004994
1  0.068021  0.997643  0.009069
2  0.041630  0.999124  0.004163
3  0.094800  0.995395  0.014220
4  0.108059  0.994144  0.000000

In [ ]:
Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the
values to a range of -1 to 1.

In [7]:
import numpy as np  
data = np.array([1, 5, 10, 15, 20])  
min_value = np.min(data)  
max_value = np.max(data)  
new_min = -1  
new_max = 1  
scaled_data = ((data - min_value) / (max_value - min_value)) * (new_max - new_min) + new_min  
scaled_data

array([-1.        , -0.57894737, -0.05263158,  0.47368421,  1.        ])